//
// Generated file, do not edit! Created by nedtool 4.6 from WebRequest.msg.
//

#ifndef _WEBREQUEST_M_H_
#define _WEBREQUEST_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>WebRequest.msg:1</tt> by nedtool.
 * <pre>
 * message WebRequest
 * {
 *     bool served;
 *     simtime_t startTime;
 *     int requestNumber;
 * }
 * </pre>
 */
class WebRequest : public ::cMessage
{
  protected:
    bool served_var;
    simtime_t startTime_var;
    int requestNumber_var;

  private:
    void copy(const WebRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WebRequest&);

  public:
    WebRequest(const char *name=NULL, int kind=0);
    WebRequest(const WebRequest& other);
    virtual ~WebRequest();
    WebRequest& operator=(const WebRequest& other);
    virtual WebRequest *dup() const {return new WebRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getServed() const;
    virtual void setServed(bool served);
    virtual simtime_t getStartTime() const;
    virtual void setStartTime(simtime_t startTime);
    virtual int getRequestNumber() const;
    virtual void setRequestNumber(int requestNumber);
};

inline void doPacking(cCommBuffer *b, WebRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WebRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef _WEBREQUEST_M_H_

